# Generated by Django 5.2.14 on 2026-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_roll_no_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='TEMP100', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
