# Generated by Django 5.2.14 on 2026-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_department_remove_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='TEMP001', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
