# Generated by Django 5.2.14 on 2026-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacher_email_remove_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='Teacher', max_length=50),
        ),
    ]
